services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    # volumes:
      # - ./backend:/app
      # - ./backend/data/src_images:/app/data/src_images
      # - ./backend/data/markuped_images:/app/data/markuped_images
    environment:
      - FLASK_ENV=development
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # volumes:
    # - ./frontend:/app
    #   # - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true